---
apiVersion: v1
kind: Service
metadata:
  name: resume-svc
spec:
  selector:
    #+operator-builder:collection:field:name="profile.firstName",type=string,default="John",replace="john"
    #+operator-builder:collection:field:name="profile.lastName",type=string,default="Doe",replace="doe"
    resume.jefedavis.dev/candidate: johndoe
  ports:
    - port: 8080
      targetPort: 1313
