/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package resumes

import (
	v1alpha1resumes "github.com/jefedavis/resume-operator/apis/resumes/v1alpha1"
	v1alpha1jobexperience "github.com/jefedavis/resume-operator/apis/resumes/v1alpha1/experience"
)

// Code generated by operator-builder. DO NOT EDIT.

// JobExperienceLatestGroupVersion returns the latest group version object associated with this
// particular kind.
var JobExperienceLatestGroupVersion = v1alpha1resumes.GroupVersion

// JobExperienceLatestSample returns the latest sample manifest associated with this
// particular kind.
var JobExperienceLatestSample = v1alpha1jobexperience.Sample(false)
