---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-profile
  labels:
    app.kubernetes.io/name: hugo
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: resume
    app.kubernetes.io/instance: resume-johndoe
data:
  profile.yaml: |-
    ---
    basicInfo:
      firstName: FirstName
      lastName: LastName
      photo: img/avatar.jpg
      contacts:
        - icon: fa-solid fa-phone
          info: PhoneNumber
        - icon: fa-solid fa-envelope
          info: Email
        - icon: fa-brands fa-linkedin
          info: LinkedInURL
        - icon: fa-brands fa-github
          info: GitHubURL
        - icon: fa-solid fa-map-marker-alt
          info: Location
    overview: Overview
    coreCompetencies: CoreCompetencies
    projects: Projects
    skills: Skills