---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-cert
  labels:
    app.kubernetes.io/name: hugo
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: resume
    app.kubernetes.io/instance: resume-johndoe
data:
  VCP-DCV.yaml: |-
    ---
    title: Title
    issuer: Issuer
    earnedDate: 2006-01-02
    alias: Alias
    validationURL: ValidationURL
    imageURL: ImageURL