---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-experience
  labels:
    resume.jefedavis.dev/candidate: johndoe
data:
  vmware.yaml: |-
    ---
    employer: Employer
    location: Location
    startDate: 2006-01-02
    endDate: Present
    positions:
      - title: Title
        startDate: 2006-01-03
        endDate: 2006-01-04
        highlights: Highlights