---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume
  labels:
    app.kubernetes.io/name: hugo
    app.kubernetes.io/component: webfront
    app.kubernetes.io/part-of: resume
    app.kubernetes.io/instance: resume-johndoe
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - example.com
      secretName: resume-tls
  rules:
  - host: example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: resume-svc
            port: 
              number: 8080
      - pathType: Prefix
        path: "/convert"
        backend:
          service:
            name: pdf-converter-svc
            port: 
              number: 3000
